# Generated by Django 3.2.11 on 2022-02-09 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_start_date'),
        ('students', '0009_alter_student_enroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
