# Generated by Django 3.2.11 on 2022-06-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_lecture_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='students.Student'),
        ),
    ]
