# Generated by Django 3.2.11 on 2022-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('age', models.IntegerField(default=20)),
                ('subject', models.CharField(max_length=64, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('students', models.ManyToManyField(to='students.Student')),
            ],
        ),
    ]
