# Generated by Django 3.2.11 on 2022-01-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20220127_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
    ]
