# Generated by Django 3.2.11 on 2022-02-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_start_date'),
        ('teachers', '0005_alter_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
    ]
