# Generated by Django 3.2.11 on 2022-06-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Teacher'), (2, 'Mentor')], default=1),
        ),
    ]
