# Generated by Django 3.2.11 on 2022-02-09 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20220207_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 18, 46, 42, 100547)),
        ),
    ]
