# Generated by Django 3.2.11 on 2022-02-09 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 18, 47, 22, 842353)),
        ),
    ]
